<?php
/**
 * File which holds the version of Orbit Application.
 *
 * @author Rio Astamal <me@rioastamal.net>
 */

/**
 * Main constant storing app version.
 *
 * Version number are formed from X.Y, where:
 *   X: Major version
 *   Y: Minor version
 */
define('ORBIT_APP_VERSION', '1.0');

/**
 * Main constant storing application build number. This number should be
 * generated by the build system (continuous integration) such as Jenkins.
 */
define('ORBIT_APP_BUILD_NUMBER', 0);

/**
 * Constant storing codename.
 */
define('ORBIT_APP_CODENAME', 'Sputnik');

/**
 * Constant storing the release date, ISO 8601.
 */
define('ORBIT_APP_RELEASE_DATE', '');

/**
 * Constanct storing the build date, ISO 8601
 */
define('ORBIT_APP_BUILD_DATE', '');
